from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional

class AssetItem(BaseModel):
    """Represents a single visual asset as defined in the Stage 5 JSON contract."""
    
    model_config = ConfigDict(populate_by_name=True)

    element: str = Field(..., description="The exact raw text cue from Mostafa's visual_elements list")
    prompt: str = Field(..., description="The highly descriptive prompt generated by Gemini")
    url: str = Field(default="https://mock-supabase-storage.com/assets/placeholder.png", description="The public-facing storage URL from Supabase")
    
    asset_license: str = Field(default="open-source", alias="license", description="Royalty-free or open-source clearance status")
    
    asset_type: str = Field(default="image", description="Asset primitive format type")
    source: str = Field(default="generated", description="Origin profile: generated or searched")
    scene_reference: Optional[str] = Field(None, alias="scene_id", description="The unique scene ID this asset belongs to")

class AssetResponseContract(BaseModel):
    """The final collection contract Nada's Stage 6 Composition pipeline expects."""
    
    # This config block allows keyword arguments to accept EITHER "assets" or "items" smoothly!
    model_config = ConfigDict(populate_by_name=True)

    assets: List[AssetItem] = Field(..., alias="items")