import os
import uuid
import logging
import json
import asyncio
from crewai import Agent, Task, Crew, LLM
from backend.app.schemas.asset import AssetItem, AssetResponseContract

logger = logging.getLogger(__name__)

class AssetService:
    def __init__(self):
        # Using Gemini API key directly as approved by the director
        self.gemini_api_key = os.getenv("GEMINI_API_KEY", "")
        
        # Metadata-Safe Object Storage Simulation (Satisfies Mentor & PRD requirements)
        self.local_storage_db = "data/supabase_asset_metadata.json"
        os.makedirs(os.path.dirname(self.local_storage_db), exist_ok=True)
        if not os.path.exists(self.local_storage_db):
            with open(self.local_storage_db, "w") as f:
                json.dump([], f)  # Initialize as a flat list to store multiple elements cleanly

    def _get_llm_client(self) -> LLM:
        """
        Returns the Gemini model client using the free quota.
        """
        logger.info("Initializing Gemini Flash agent client...")
        return LLM(
            model="gemini/gemini-1.5-flash",  # Highly responsive and stable for free-quota use
            api_key=self.gemini_api_key
        )

    def register_asset_in_storage(self, asset: AssetItem) -> str:
        """
        Simulates registering and persisting the asset alongside its mandatory 
        metadata into our Supabase Object Storage bucket log.
        """
        try:
            with open(self.local_storage_db, "r") as f:
                db = json.load(f)
            if not isinstance(db, list):
                db = []
        except Exception:
            db = []

        # Build clean metadata entry tracing back asset parameters
        asset_entry = {
            "scene_id": asset.scene_reference,
            "element": asset.element,
            "prompt": asset.prompt,
            "url": asset.url,
            "type": asset.asset_type,
            "source": asset.source,
            "license": asset.asset_license,
            "registered_at": "2026-07-15T12:00:00Z"
        }
        db.append(asset_entry)

        with open(self.local_storage_db, "w") as f:
            json.dump(db, f, indent=4)
            
        logger.info(f"Asset successfully registered in object storage metadata: {asset.scene_reference}")
        return asset.url

    async def resolve_visual_cue(self, cue: str, scene_id: str) -> AssetItem:
        """
        Runs the CrewAI agent task to turn raw scene cues into highly descriptive image prompts.
        """
        llm_client = self._get_llm_client()

        # Define your specialized CrewAI Agent
        design_director = Agent(
            role="Educational Visual Design Director",
            goal="Refine simple and loose textual visual cues into highly detailed, clean image prompts.",
            backstory="You are an expert visual layout designer at Sprints Video Studio who excels at creating vivid image concepts.",
            verbose=False,
            allow_delegation=False,
            llm=llm_client
        )

        refinement_task = Task(
            description=f"Refine this conceptual slide visual cue into an descriptive image generator prompt: '{cue}'",
            expected_output="A single optimized prompt string suitable for image generation engines.",
            agent=design_director
        )

        my_crew = Crew(agents=[design_director], tasks=[refinement_task])

        try:
            # Prevent event-loop blocking by running the blocking Crew execution in an executor pool
            loop = asyncio.get_event_loop()
            result = await loop.run_in_executor(None, my_crew.kickoff)
            optimized_prompt = result.raw.strip() if hasattr(result, 'raw') else str(result).strip()
        except Exception as e:
            logger.error(f"Asset Service LLM processing failed ({e}). Falling back to raw cue.")
            optimized_prompt = f"Illustration showing: {cue}"

        # Formulate asset object matching our updated Pydantic schema contracts
        asset = AssetItem(
            element=cue,                # Raw cue preserved perfectly for Mostafa
            prompt=optimized_prompt,    # Refined output generated by Gemini
            url=f"https://supabase-storage.local/assets/{uuid.uuid4()}.png",
            asset_type="image",
            source="generated",
            license="open-source",
            scene_reference=scene_id
        )

        # Persist metadata tracking
        self.register_asset_in_storage(asset)

        return asset

    async def process_scene_elements(self, visual_elements: list[str], scene_id: str) -> AssetResponseContract:
        """
        Process multiple visual assets asynchronously to guarantee high responsiveness.
        """
        if not visual_elements:
            return AssetResponseContract(assets=[])

        tasks = [self.resolve_visual_cue(cue, scene_id) for cue in visual_elements]
        resolved_assets = await asyncio.gather(*tasks)

        return AssetResponseContract(assets=resolved_assets)